lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # path to your private key
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # path to your public key
    pass_phrase:      null # No passphrase because we used unencrypted key
    token_ttl:        3600
