nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: [
                "http://localhost:5173",
                "http://localhost:4200",
                "*",
                "http://localhost",
            ] # ← add your actual frontend origin here
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Authorization"]
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        max_age: 3600

    paths:
        "^/api/":
            allow_origin:
                ["http://localhost:5173", "http://localhost:4200", "*"]
            allow_headers: ["Content-Type", "Authorization"]
            allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allow_credentials: true
